#server
tomcat:
  ajp:
    protocol: AJP/1.3
    port: '18009'
    enabled: 'true'
server:
  servlet:
    encoding:
      chartset: UTF-8
#jsp
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
devtools:
  livereload:
    enabled: 'true'
#cert
cert:
  path: /testcert/test